//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigiSalud.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class encuesta
    {
        public int id { get; set; }
        public string FormatoEnPapel { get; set; }
        public string PartiCipa { get; set; }
        public Nullable<int> Edad { get; set; }
        public string Sexo { get; set; }
        public string CiudadOrigen { get; set; }
        public string CiudadActual { get; set; }
        public string Retraso { get; set; }
        public Nullable<int> SemestresAtrasados { get; set; }
        public bool Dificultades { get; set; }
        public bool ProblemasEcon { get; set; }
        public bool ProblemasSalud { get; set; }
        public bool ProblemasSaludMen { get; set; }
        public bool ProblemasFamil { get; set; }
        public bool CalamidadDomes { get; set; }
        public Nullable<int> Estudio { get; set; }
        public Nullable<int> Deporte { get; set; }
        public Nullable<int> Culturales { get; set; }
        public Nullable<int> Entretenimiento { get; set; }
        public Nullable<int> Trabajo { get; set; }
        public Nullable<int> Religiosas { get; set; }
        public Nullable<int> Otras { get; set; }
        public string CondicionMedica { get; set; }
        public string CondicionMedicaDet { get; set; }
        public bool MadreEnfMen { get; set; }
        public bool PadreEnfMen { get; set; }
        public bool HermanoEnfMen { get; set; }
        public bool ParejaEnfMen { get; set; }
        public bool AbueloEnfMen { get; set; }
        public bool PrimoEnfMen { get; set; }
        public bool SobrinoEnfMen { get; set; }
        public bool HijoEnfMen { get; set; }
        public bool TioEnfMen { get; set; }
        public bool MadreDep { get; set; }
        public bool PadreDep { get; set; }
        public bool HermanoDep { get; set; }
        public bool ParejaDep { get; set; }
        public bool AbueloDep { get; set; }
        public bool PrimoDep { get; set; }
        public bool SobrinoDep { get; set; }
        public bool HijoEnfDep { get; set; }
        public bool TioEnfDep { get; set; }
        public bool MadreAns { get; set; }
        public bool PadreAns { get; set; }
        public bool HermanoAns { get; set; }
        public bool ParejaAns { get; set; }
        public bool AbueloAns { get; set; }
        public bool PrimoAns { get; set; }
        public bool SobrinoAns { get; set; }
        public bool HijoEnfAns { get; set; }
        public bool TioEnfAns { get; set; }
        public bool MadreEsq { get; set; }
        public bool PadreEsq { get; set; }
        public bool HermanoEsq { get; set; }
        public bool ParejaEsq { get; set; }
        public bool AbueloEsq { get; set; }
        public bool PrimoEsq { get; set; }
        public bool SobrinoEsq { get; set; }
        public bool HijoEnfEsq { get; set; }
        public bool TioEnfEsq { get; set; }
        public bool MadreLicDrog { get; set; }
        public bool PadreLicDrog { get; set; }
        public bool HermanoLicDrog { get; set; }
        public bool ParejaLicDrog { get; set; }
        public bool AbueloLicDrog { get; set; }
        public bool PrimoLicDrog { get; set; }
        public bool SobrinoLicDrog { get; set; }
        public bool HijoEnfLicDrog { get; set; }
        public bool TioEnfLicDrog { get; set; }
        public bool MadreOtra { get; set; }
        public bool PadreOtra { get; set; }
        public bool HermanoOtra { get; set; }
        public bool ParejaOtra { get; set; }
        public bool AbueloOtra { get; set; }
        public bool PrimoOtra { get; set; }
        public bool SobrinoOtra { get; set; }
        public bool HijoEnfOtra { get; set; }
        public bool TioEnfOtra { get; set; }
        public string MadreTiempoD { get; set; }
        public string PadreTiempoD { get; set; }
        public string HermanoTiempoD { get; set; }
        public string ParejaTiempoD { get; set; }
        public string AbueloTiempoD { get; set; }
        public string PrimoTiempoD { get; set; }
        public string SobrinoTiempoD { get; set; }
        public string HijoEnfTiempoD { get; set; }
        public string TioEnfTiempoD { get; set; }
        public bool MadreTrat { get; set; }
        public bool PadreTrat { get; set; }
        public bool HermanoTrat { get; set; }
        public bool ParejaTrat { get; set; }
        public bool AbueloTrat { get; set; }
        public bool PrimoTrat { get; set; }
        public bool SobrinoTrat { get; set; }
        public bool HijoTrat { get; set; }
        public bool TioEnfTrat { get; set; }
        public string Alcohol { get; set; }
        public string Nicotina { get; set; }
        public string Cannabis { get; set; }
        public string Cocaina { get; set; }
        public string Sedantes { get; set; }
        public string Opiaceos { get; set; }
        public string Otros { get; set; }
        public string LoUsa { get; set; }
        public bool SmarthPhone { get; set; }
        public bool Tablet { get; set; }
        public bool ComputadorFamiliar { get; set; }
        public bool ComputadorPropio { get; set; }
        public bool PortatilFamiliar { get; set; }
        public bool PortatilPropio { get; set; }
        public bool TV { get; set; }
        public bool Consola { get; set; }
        public bool SalaHogar { get; set; }
        public bool Habitacion { get; set; }
        public bool Universidad { get; set; }
        public bool TrabajoI { get; set; }
        public bool CasaAmigo { get; set; }
        public bool CasaFamiliar { get; set; }
        public bool OtrosPublicos { get; set; }
        public bool OtraVia { get; set; }
        public bool InternetCasa { get; set; }
        public bool InternetMobil { get; set; }
        public bool InternetTrabajo { get; set; }
        public bool InternetUniversidad { get; set; }
        public bool InternetPublico { get; set; }
        public Nullable<System.DateTime> fechaDiligen { get; set; }
    }
}
